//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 12/5/2012 4:09:05 PM
namespace AmazonProductAdvtApi
{
    
    /// <summary>
    /// There are no comments for ssceDBEntities in the schema.
    /// </summary>
    public partial class ssceDBEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new ssceDBEntities object using the connection string found in the 'ssceDBEntities' section of the application configuration file.
        /// </summary>
        public ssceDBEntities() : 
                base("name=ssceDBEntities", "ssceDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ssceDBEntities object.
        /// </summary>
        public ssceDBEntities(string connectionString) : 
                base(connectionString, "ssceDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ssceDBEntities object.
        /// </summary>
        public ssceDBEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "ssceDBEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for SearchIndexes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<SearchIndex> SearchIndexes
        {
            get
            {
                if ((this._SearchIndexes == null))
                {
                    this._SearchIndexes = base.CreateQuery<SearchIndex>("[SearchIndexes]");
                }
                return this._SearchIndexes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<SearchIndex> _SearchIndexes;
        /// <summary>
        /// There are no comments for SearchIndexes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSearchIndexes(SearchIndex searchIndex)
        {
            base.AddObject("SearchIndexes", searchIndex);
        }
    }
    /// <summary>
    /// There are no comments for ssceDBModel.SearchIndex in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ssceDBModel", Name="SearchIndex")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SearchIndex : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SearchIndex object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="title">Initial value of Title.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static SearchIndex CreateSearchIndex(int id, string title)
        {
            SearchIndex searchIndex = new SearchIndex();
            searchIndex.ID = id;
            searchIndex.Title = title;
            return searchIndex;
        }
        /// <summary>
        /// There are no comments for property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Title;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTitleChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTitleChanged();
    }
}
